name: Weather-App-Build
on:
  push:
    branches:
      - master
    paths:
      - 'application/**'
      - '.github/workflows/app.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push image to ECR
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Log in to ECR
        working-directory: ./application
        run: make login
        env:
          ACCOUNTID: ${{ secrets.ACCOUNTID }}
          AWSREGION: ${{ secrets.AWSREGION }}
          REPONAME: ${{ secrets.REPONAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 

      - name: Build weather-app image
        working-directory: ./application
        env:
          ACCOUNTID: ${{ secrets.ACCOUNTID }}
          AWSREGION: ${{ secrets.AWSREGION }}
          REPONAME: ${{ secrets.REPONAME }}
        run: make build

      - name: Push weather-app image to ECR
        working-directory: ./application
        env:
          ACCOUNTID: ${{ secrets.ACCOUNTID }}
          AWSREGION: ${{ secrets.AWSREGION }}
          REPONAME: ${{ secrets.REPONAME }}
        run: make push


