name: Deploy-Infrastructure
on:
  push:
    branches:
      - master
    paths:
      - 'infrastructure/**'
      - '.github/workflows/main.yml'
      
jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
      GODADDY_API_KEY: ${{ secrets.GODADDY_KEY }}
      GODADDY_API_SECRET: ${{ secrets.GODADDY_SECRET }}
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      working-directory: ./infrastructure
      run: make run_plan       

  terraform_apply:
    environment:
      name: approval
    needs: terraform_plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
      GODADDY_API_KEY: ${{ secrets.GODADDY_KEY }}
      GODADDY_API_SECRET: ${{ secrets.GODADDY_SECRET }}
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      working-directory: ./infrastructure
      run: make run_plan
    - name: Terraform_Apply
      working-directory: ./infrastructure
      run: make run_apply  




