name: Deploy-Infrastructure
on:
  push:
    branches:
      - master
    paths:
      - 'infrastructure/**'
      - '.github/workflows/main.yml'
      
jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
      GODADDY_KEY: ${{ secrets.GODADDY_KEY }}
      GODADDY_SECRET: ${{ secrets.GODADDY_SECRET }}
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      working-directory: ./infrastructure
      run: make run_plan       

  terraform_apply:
    environment:
      name: approval
    needs: terraform_plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
      GODADDY_KEY: ${{ secrets.GODADDY_KEY }}
      GODADDY_SECRET: ${{ secrets.GODADDY_SECRET }}
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      working-directory: ./infrastructure
      run: make run_plan
    - name: Terraform_Apply
      working-directory: ./infrastructure
      run: make run_apply  

  post_to_slack:
    needs: terraform_apply
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
      # Slack channel id, channel name, or user id to post message.
      # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: 'C035G62LAUU'
        # For posting a simple plain text message
        slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
